class Settings:
    CONFIG_FILENAME = "config.json"
    MODEL_FILENAME = "model.pth"
    TRANSFORMER_MODEL_TYPE = "transformer"
    CLASSIFICATION_HEAD_MODEL_TYPE = "classification_head"
    GPT2_MODEL_TYPE = "gpt2"
    MERGED_MODEL_TYPE = "merged"
    TRANSFORMER_SRC_PAD_IDX = 0
    TRANSFORMER_TRG_PAD_IDX = 0
    TRANSFORMER_EMPTY_TOKEN = "<EMPTY>"
    TRANSFORMER_SOS_TOKEN = "<sos>"
    TRANSFORMER_EOS_TOKEN = "<eos>"
    TRANSFORMER_OOV_TOKEN = "<OOV>"
    TRANSFORMER_EMBED_SIZE = 1024
    TRANSFORMER_NUM_LAYERS = 6
    TRANSFORMER_HEADS = 8
    GPT2_USE_CUSTOM_WEIGHTS = False
